[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
nnoremap <silent> ,ud :Denite directory_mru<CR>
nnoremap <silent> ,uf :Denite file_mru<CR>
'''
hook_post_source = '''
call denite#custom#source('directory_mru', 'matchers', ['matcher_fuzzy'])
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimfiler'
